#pragma once

#include "NativeGameplayTags.h"

namespace RlsLocomotionModeTags
{
	ALS_REFACTOR_REMAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grounded)
	ALS_REFACTOR_REMAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InAir)
}

namespace RlsRotationModeTags
{
	ALS_REFACTOR_REMAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(VelocityDirection)
	ALS_REFACTOR_REMAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ViewDirection)
}

namespace RlsStanceTags
{
	ALS_REFACTOR_REMAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Standing)
	ALS_REFACTOR_REMAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Crouching)
}

namespace RlsGaitTags
{
	ALS_REFACTOR_REMAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Walking)
	ALS_REFACTOR_REMAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Running)
	ALS_REFACTOR_REMAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprinting)
}

namespace RlsLocomotionActionTags
{
	ALS_REFACTOR_REMAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(None)
	ALS_REFACTOR_REMAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rolling)
	ALS_REFACTOR_REMAKE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mantling)
}

